name: CI
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Run install
        run: pnpm run ci

      - name: Run build
        run: pnpm build

      - name: Run lint
        run: pnpm lint

      - name: Run test
        run: pnpm test
